# Generated by Django 3.0.5 on 2020-05-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destination',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dest_name', models.TextField(max_length=30)),
                ('dest_desc', models.TextField()),
                ('dest_price', models.IntegerField()),
                ('dest_img', models.ImageField(upload_to='static/images')),
            ],
        ),
    ]
