# Generated by Django 3.0.5 on 2020-05-05 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0003_blogs'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 5, 5, 29, 58, 553966)),
        ),
    ]
