# Generated by Django 3.0.5 on 2020-05-05 05:32

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0005_auto_20200505_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='blog_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 5, 5, 32, 39, 321197, tzinfo=utc)),
        ),
    ]
