# Generated by Django 3.0.5 on 2020-05-05 05:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0006_auto_20200505_0532'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_head', models.CharField(max_length=100)),
                ('blog_para1', models.TextField()),
                ('blog_para2', models.TextField()),
                ('blog_date', models.DateField(verbose_name=datetime.datetime(2020, 5, 5, 5, 34, 31, 315658, tzinfo=utc))),
                ('blog_author', models.CharField(max_length=30)),
            ],
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
    ]
