# Generated by Django 3.0.5 on 2020-05-07 19:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0008_auto_20200507_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 7, 19, 22, 52, 545038, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para1',
            field=models.TextField(max_length=500),
        ),
    ]
