# Generated by Django 3.0.5 on 2020-05-08 18:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0009_auto_20200507_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_para2',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 8, 18, 36, 59, 967732, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para1',
            field=models.TextField(),
        ),
    ]
