# Generated by Django 3.0.5 on 2020-05-08 20:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0010_auto_20200508_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_para2',
            field=models.TextField(default=True),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 8, 20, 18, 51, 20564, tzinfo=utc)),
        ),
    ]
