# Generated by Django 3.0.5 on 2020-05-09 19:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0011_auto_20200508_2018'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_highlight',
            field=models.CharField(default='None', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 9, 19, 20, 25, 286435, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_para2',
            field=models.TextField(),
        ),
    ]
