# Generated by Django 3.0.5 on 2020-05-10 11:24

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0012_auto_20200509_1921'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_author',
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 10, 11, 24, 33, 435247, tzinfo=utc)),
        ),
    ]
