# Generated by Django 3.0.5 on 2020-05-10 11:30

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0013_auto_20200510_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_author',
            field=models.CharField(default='none', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 10, 11, 30, 26, 163660, tzinfo=utc)),
        ),
    ]
