# Generated by Django 3.0.5 on 2020-05-10 19:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0020_auto_20200510_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(verbose_name=datetime.datetime(2020, 5, 10, 19, 26, 33, 513194, tzinfo=utc)),
        ),
    ]
