# Generated by Django 3.0.5 on 2020-05-10 19:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0031_auto_20200510_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_date',
        ),
    ]
