# Generated by Django 3.0.5 on 2020-05-10 19:52

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0032_remove_blog_blog_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 19, 52, 27, 481977, tzinfo=utc)),
        ),
    ]
