# Generated by Django 3.0.5 on 2020-05-10 20:03

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0038_auto_20200510_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.TextField(default=datetime.datetime(2020, 5, 10, 20, 3, 17, 548428, tzinfo=utc)),
        ),
    ]
