# Generated by Django 3.0.5 on 2020-05-10 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0040_auto_20200510_2004'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Blog',
        ),
    ]
