# Generated by Django 3.0.5 on 2020-05-10 20:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0041_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_head', models.CharField(max_length=100)),
                ('blog_para1', models.TextField()),
                ('blog_para2', models.TextField()),
                ('blog_date', models.TextField(default=datetime.datetime(2020, 5, 10, 20, 25, 3, 975105, tzinfo=utc))),
                ('blog_author', models.CharField(max_length=30)),
                ('blog_highlight', models.CharField(max_length=100)),
            ],
        ),
    ]
