# Generated by Django 3.0.5 on 2020-05-10 20:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0047_auto_20200510_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.TextField(default=datetime.datetime(2020, 5, 10, 20, 43, 18, 428934, tzinfo=utc)),
        ),
    ]
