# Generated by Django 3.0.5 on 2020-05-11 09:29

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0049_auto_20200510_2048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.TextField(default=datetime.datetime(2020, 5, 11, 9, 29, 12, 973036, tzinfo=utc)),
        ),
    ]
