# Generated by Django 3.0.5 on 2020-05-12 20:31

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('covidstatus', '0058_auto_20200512_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_date',
            field=models.TextField(default=datetime.datetime(2020, 5, 12, 20, 31, 56, 261179, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='img_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 20, 31, 56, 262000)),
        ),
    ]
