# Generated by Django 3.0.5 on 2020-05-10 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_remove_profile_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postnew',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_title', models.CharField(max_length=100)),
                ('post_content', models.TextField()),
                ('post_owner', models.CharField(max_length=100)),
            ],
        ),
    ]
