# Generated by Django 3.0.5 on 2020-05-10 20:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_auto_20200510_2036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnew',
            name='post_date',
            field=models.DateField(default=datetime.datetime(2020, 5, 10, 20, 39, 20, 891677, tzinfo=utc)),
        ),
    ]
