# Generated by Django 3.0.5 on 2020-05-10 20:48

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_auto_20200510_2043'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.ImageField(default='static/default.jpeg', upload_to='static/profile_pics'),
        ),
        migrations.AlterField(
            model_name='postnew',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 10, 20, 48, 51, 889541)),
        ),
    ]
