# Generated by Django 3.0.5 on 2020-05-11 09:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20200511_0929'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profile',
            new_name='Profilenew',
        ),
        migrations.AlterField(
            model_name='postnew',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 9, 31, 57, 769648)),
        ),
    ]
