# Generated by Django 3.0.5 on 2020-05-11 09:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_auto_20200511_0932'),
    ]

    operations = [
        migrations.AddField(
            model_name='profilenew',
            name='profileid',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='profilenew',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 9, 51, 57, 278022)),
        ),
        migrations.AlterField(
            model_name='postnew',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 9, 51, 57, 278993)),
        ),
    ]
