# Generated by Django 3.0.5 on 2020-05-11 09:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_auto_20200511_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnew',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 9, 58, 44, 627977)),
        ),
        migrations.AlterField(
            model_name='profilenew',
            name='image',
            field=models.ImageField(upload_to='static/profile_pics'),
        ),
        migrations.AlterField(
            model_name='profilenew',
            name='updated_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 11, 9, 58, 44, 626938)),
        ),
    ]
