# Generated by Django 3.0.5 on 2020-05-12 19:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_auto_20200512_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postnew',
            name='post_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 12, 19, 13, 42, 148455)),
        ),
    ]
